<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Attivo',
    'Are you sure you want to delete this item?' => 'Sei sicuro di voler cancellare questo elemento?',
    'Change at your own risk' => 'Cambia a tuo rischio',
    'Create' => 'Crea',
    'Create {modelClass}' => 'Crea {modelClass}',
    'Created' => 'Creato',
    'Delete' => 'Cancella',
    'ID' => '',
    'Key' => 'Chiave',
    'Modified' => 'Modificato',
    'Reset' => 'Resetta',
    'Search' => 'Cerca',
    'Section' => 'Sezione',
    'Setting' => 'Impostazione',
    'Settings' => 'Impostazioni',
    'Successfully saved settings on {section}' => 'Impostazioni salvata correttamente nella sezione {section}',
    'Type' => 'Tipo',
    'Update' => 'Aggiorna',
    'Update {modelClass}: ' => 'Aggiorna {modelClass}: ',
    'Value' => 'Valore',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" esiste già per questa sezione.',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" deve essere un oggetto JSON valido',
    'Please select correct type' => 'Seleziona il tipo corretto',
    'string' => 'stringa',
    'integer' => 'intero',
    'boolean' => 'booleano',
    'float' => 'float',
    'email' => 'E-mail',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'ogetto',
];
