<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активная',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить эту запись?',
    'Change at your own risk' => 'Меняете на свой страх и риск',
    'Create' => 'Создать',
    'Create {modelClass}' => 'Создание {modelClass}',
    'Created' => 'Создано',
    'Delete' => 'Удалить',
    'ID' => '',
    'Key' => 'Ключ',
    'Modified' => 'Отредактировано',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Section' => 'Раздел',
    'Setting' => 'Настройка',
    'Settings' => 'Настройки',
    'Type' => 'Тип',
    'Update' => 'Редактировать',
    'Update {modelClass}: ' => 'Редактирование {modelClass}: ',
    'Value' => 'Значение',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" уже существует для данного раздела',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" должен содержать корректный JSON объект',
    'Please select correct type' => 'Выберите допустимый тип',
    'string' => 'Строка',
    'integer' => 'Целое число',
    'boolean' => '0 или 1',
    'float' => 'Число',
    'email' => 'E-mail',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'JSON',
    'Successfully saved settings on {section}' => 'Настройки удачно сохранены для {section}'
];
