<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Activo',
    'Are you sure you want to delete this item?' => '¿Estás seguro que quieres eliminar esa configuración?',
    'Change at your own risk' => 'Cámbialo bajo tu propio riesgo',
    'Create' => 'Crear',
    'Create {modelClass}' => 'Crear {modelClass}',
    'Created' => 'Creado',
    'Delete' => 'Eliminar',
    'ID' => 'ID',
    'Key' => 'Clave',
    'Modified' => 'Modificado',
    'Please select correct type' => 'Por favor selecciona el tipo correcto',
    'Reset' => 'Restablecer',
    'Search' => 'Buscar',
    'Section' => 'Sección',
    'Setting' => 'Configuración',
    'Settings' => 'Configuraciones',
    'Successfully saved settings on {section}' => 'Configuración guardada correctamente en la sección {section}',
    'Type' => 'Tipo',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'Value' => 'Valor',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" ya existe en esta sección.',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" debe ser un objeto JSON válido',
    'string' => 'Cadena de texto',
    'integer' => 'Entero',
    'boolean' => 'Booleano',
    'float' => 'Decimal',
    'email' => 'Correo electrónico',
    'ip' => 'Dirección IP',
    'url' => 'URL',
    'object' => 'Objeto',
];
