<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '有效',
    'Are you sure you want to delete this item?' => '确定要删除该项目吗?',
    'Change at your own risk' => '更改需要自行承担风险',
    'Create' => '创建',
    'Create {modelClass}' => '创建 {modelClass}',
    'Created' => '已创建',
    'Delete' => '删除',
    'ID' => 'ID',
    'Key' => 'Key',
    'Modified' => '已修改',
    'Reset' => '重置',
    'Search' => '搜索',
    'Section' => '分组',
    'Setting' => '设置',
    'Settings' => '设置',
    'Type' => '类型',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass}: ',
    'Value' => '值',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" 已经存在于该分组中.',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" 必须是合法的JSON对象',
    'Please select correct type' => '请选择正常的类型',
    'string' => '字符串',
    'integer' => '整数',
    'boolean' => '布尔值',
    'float' => '浮点型',
    'email' => '邮箱',
    'ip' => 'IP',
    'url' => '链接',
    'object' => '对象',
    'Successfully saved settings on {section}'=>'{section} 的设置保存成功'
];
