<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Are you sure you want to delete this item?' => '',
    'Change at your own risk' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Created' => '',
    'Delete' => '',
    'ID' => '',
    'Key' => '',
    'Modified' => '',
    'Reset' => '',
    'Search' => '',
    'Section' => '',
    'Setting' => '',
    'Settings' => '',
    'Type' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Value' => '',
    '{attribute} "{value}" already exists for this section.' => '',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" must be a valid JSON object',
    'Please select correct type' => 'Please select correct type',
    'string' => 'String',
    'integer' => 'Integer',
    'boolean' => 'Boolean',
    'float' => 'Number',
    'email' => 'E-mail',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'JSON',
];
