<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'พร้อมทำงาน',
    'Are you sure you want to delete this item?' => 'คุณแน่ใจใช่ไหมว่าต้องการที่จะลบข้อมูลนี้?',
    'Change at your own risk' => 'เปลี่ยนข้อมูลมีความเสี่ยง',
    'Create' => 'สร้าง',
    'Create {modelClass}' => 'สร้าง {modelClass}',
    'Created' => 'สร้าง',
    'Delete' => 'ลบ',
    'ID' => 'ไอดี',
    'Key' => 'คีย์',
    'Modified' => 'แก้ไข',
    'Reset' => 'คืนค่า',
    'Search' => 'ค้นหา',
    'Section' => 'ส่วน',
    'Setting' => 'การตั้งค่า',
    'Settings' => 'การตั้งค่า',
    'Type' => 'ชนิด',
    'Update' => 'ปรับปรุง',
    'Update {modelClass}: ' => 'ปรับปรุง {modelClass}: ',
    'Value' => 'ค่า',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" มีแล้วในะระบบ',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" ต้องอยู่ในรูปแบบ JSON',
    'Please select correct type' => 'เลือกให้ตรงชนิด',
    'string' => 'ตัวอักษร',
    'integer' => 'ตัวเลข',
    'boolean' => '0 หรือ 1',
    'float' => 'ค่าทศนิยม',
    'email' => 'E-mail',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'JSON',
];
