<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '有效',
    'Are you sure you want to delete this item?' => '確定要刪除該項目嗎?',
    'Change at your own risk' => '更改需要自行承擔風險',
    'Create' => '創建',
    'Create {modelClass}' => '創建 {modelClass}',
    'Created' => '已創建',
    'Delete' => '刪除',
    'ID' => 'ID',
    'Key' => 'Key',
    'Modified' => '已修改',
    'Reset' => '重置',
    'Search' => '搜尋',
    'Section' => '分組',
    'Setting' => '設置',
    'Settings' => '設置',
    'Type' => '類型',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass}: ',
    'Value' => '值',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" 已經存在於該分組中.',
        '"{attribute}" must be a valid JSON object' => '"{attribute}" 必須是合法的JSON對象',
        'Please select correct type' => '請選擇正確的類型',
    'string' => '字符串',
    'integer' => '整數',
    'boolean' => '布爾值',
    'float' => '浮點型',
    'email' => '郵箱',
    'ip' => 'IP',
    'url' => '鏈接',
    'object' => '對象',
    'Successfully saved settings on {section}'=>'{section} 的設置保存成功'
];
