<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Type' => 'Typ',
    'Section' => 'Grupa',
    'Key' => 'Klucz',
    'Value' => 'Wartość',
    'Status' => 'Status',
    'Description' => 'Opis',
    'Created Date' => 'Data utworzenia',
    'Updated Date' => 'Data aktualizacji',
    'Settings' => 'Konfiguracja',
    'Create Setting' => 'Dodaj konfigurację',
    'Select Type' => 'Wybierz typ',
    'Select Section' => 'Wybierz grupę',
    'Select Status' => 'Wybierz status',
    'Actions' => 'Akcje',
    'Active' => 'Aktywne',
    'Inactive' => 'Nieaktywne',
    'Update Setting: {0} -> {1}' => 'Edytuj konfigurację: {0} -> {1}',
    'Update Setting' => 'Edytuj konfigurację',
    'Update' => 'Aktualizuj',
    'Create' => 'Dodaj',
    'Delete' => 'Usuń',
    'Go Back' => 'Wstecz',
    'String' => 'Tekst',
    'Integer' => 'Liczba całkowita',
    'Boolean' => 'Prawda/Fałsz',
    'Float' => 'Liczba zmiennoprzecinkowa',
    'Null' => 'Null',
    'Setting has been created.' => 'Konfiguracja została dodana.',
    'Setting has been deleted.' => 'Konfiguracja została usunięta.',
    'Setting has been updated.' => 'Konfiguracja została zaktualizowana.',
    'The requested page does not exist.' => 'Szukana strona nie istnieje',
];
