<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активний',
    'Are you sure you want to delete this item?' => 'Ви впевнені, що хочете видалити цей запис?',
    'Change at your own risk' => 'Змінюєте на свій страх і ризик',
    'Create' => 'Створити',
    'Create {modelClass}' => 'Створити {modelClass}',
    'Created' => 'Створено',
    'Delete' => 'Видалити',
    'ID' => '',
    'Key' => 'Ключ',
    'Modified' => 'Відредаговано',
    'Reset' => 'Скинути',
    'Search' => 'Пошук',
    'Section' => 'Секція',
    'Settings' => 'Налаштування',
    'Setting' => 'Налаштування',
    'Type' => 'Тип',
    'Update' => 'Редагувати',
    'Update {modelClass}: ' => 'Редагування {modelClass}: ',
    'Value' => 'Значення',
];
