<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активне',
    'Are you sure you want to delete this item?' => 'Ви впевнені, що хочете видалити цей запис?',
    'Change at your own risk' => 'Змінюєте на свій страх і ризик',
    'Create' => 'Створити',
    'Create {modelClass}' => 'Створити {modelClass}',
    'Created' => 'Створено',
    'Delete' => 'Видалити',
    'ID' => '',
    'Key' => 'Ключ',
    'Modified' => 'Відредаговано',
    'Reset' => 'Скинути',
    'Search' => 'Пошук',
    'Section' => 'Секція',
    'Setting' => 'Налаштування',
    'Settings' => 'Налаштування',
    'Type' => 'Тип',
    'Update' => 'Редагувати',
    'Update {modelClass}: ' => 'Редагування {modelClass}: ',
    'Value' => 'Значення',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" уже існує в даній секції.',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" повинен містити корректний JSON об’єкт',
    'Please select correct type' => 'Оберіть корректний тип',
    'string' => 'Рядок',
    'integer' => 'Ціле число',
    'boolean' => '0 або 1',
    'float' => 'Число',
    'email' => 'E-mail',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'JSON',
];
