<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktywne',
    'Are you sure you want to delete this item?' => 'Czy usunąć wpis?',
    'Change at your own risk' => 'Zmiana na własne ryzyko',
    'Create' => 'Dodaj',
    'Create {modelClass}' => 'Dodaj {modelClass}',
    'Created' => 'Dodane',
    'Delete' => 'Usuń',
    'ID' => 'ID',
    'Key' => 'Klucz',
    'Modified' => 'Zmienione',
    'Reset' => 'Reset',
    'Search' => 'Szukaj',
    'Section' => 'Sekcja',
    'Setting' => 'Ustawienie',
    'Settings' => 'Ustawienia',
    'Type' => 'Typ',
    'Update' => 'Zmień',
    'Update {modelClass}: ' => 'Zmień {modelClass}: ',
    'Value' => 'Wartość',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" już istnieje w sekcji.',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" musi być poprawnym objektem JSON',
    'Please select correct type' => 'Proszę wybrać poprawny typ',
    'string' => 'string',
    'integer' => 'integer',
    'boolean' => 'boolean',
    'float' => 'float',
    'email' => 'e-mail',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'JSON',
];
