<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Ativo',
    'Are you sure you want to delete this item?' => 'Tem certeza que deseja excluir esse item?',
    'Change at your own risk' => 'Altere por seu próprio risco',
    'Create' => 'Criar',
    'Create {modelClass}' => 'Criar {modelClass}',
    'Created' => 'Criado',
    'Delete' => 'Excluir',
    'ID' => 'ID',
    'Key' => 'Chave',
    'Modified' => 'Modificado',
    'Please select correct type' => 'Por favor selecione o tipo correto',
    'Reset' => 'Redefinir',
    'Search' => 'Pesquisar',
    'Section' => 'Seção',
    'Setting' => 'Configuração',
    'Settings' => 'Configurações',
    'Successfully saved settings on {section}' => 'Configuração gravada corretamente na {section}',
    'Type' => 'Tipo',
    'Update' => 'Alterar',
    'Update {modelClass}: ' => 'Alterar {modelClass}: ',
    'Value' => 'Valor',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" já existe para essa seção.',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" precisa ser um objeto JSON válido',
    'string' => 'Texto',
    'integer' => 'Inteiro',
    'boolean' => 'Booleano',
    'float' => 'Decimal',
    'email' => 'E-mail',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'Objeto',
];
