<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktīvs',
    'Are you sure you want to delete this item?' => 'Vai patiešām vēlaties dzēst šo ierakstu?',
    'Change at your own risk' => 'Izmaiņas veiciet uz jūsu atbildību',
    'Create' => 'Izveidot',
    'Create {modelClass}' => 'Notiek {modelClass} izveidošana',
    'Created' => 'Izveidots',
    'Delete' => 'Dzēst',
    'ID' => '',
    'Key' => 'Atslēga',
    'Modified' => 'Labots',
    'Reset' => 'Atstatīt',
    'Search' => 'Meklēt',
    'Section' => 'Sadaļa',
    'Setting' => 'Uzstādījums',
    'Settings' => 'Uzstādījumi',
    'Type' => 'Tips',
    'Update' => 'Labot',
    'Update {modelClass}: ' => 'Labot {modelClass}: ',
    'Value' => 'Vērtība',
    '{attribute} "{value}" already exists for this section.' => '{attribute} "{value}" jau ir aktuālajā sadaļā',
    '"{attribute}" must be a valid JSON object' => '"{attribute}" jābūt korektam JSON objektam',
    'Please select correct type' => 'Izvēlaties pieejamo tipu',
    'string' => 'Rinda',
    'integer' => 'Vesels skaitlis',
    'boolean' => '0 vai 1',
    'float' => 'Decimālskaitlis',
    'email' => 'Epasts',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'JSON',
];
